Variables:

  com.axonivy.connector.sftp.server:
    dummy:
      # The host name to the SFTP server
      host: ''
      
      # The port number to the SFTP server
      port: 22
  
      # The username to the SFTP server
      username: ''
      
      # Auth type to the SFPT server
      # [enum: password, ssh]
      auth: 'password'
      
      # The password to the SFTP server
      # [password]
      password: ''
      
              # Dear Bug Hunter
              # This credential is intentionally included for educational purposes only and does not provide access to any production systems
              # Please do not submit it as part of our bug bounty program
      # The path of ssh key file to SFTP server
      sshkeyFilePath: ''
  
      # The ssh key passphrase
      sshPassphraseSecret: ''
